// <auto-generated />
using System;
using Mcc.Bot.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Mcc.Bot.Service.Migrations
{
    [DbContext(typeof(ServiceContext))]
    [Migration("20211209064516_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Mcc.Bot.Service.Models.AuthenticationToken", b =>
                {
                    b.Property<string>("Secret")
                        .HasColumnType("text");

                    b.Property<bool>("CanManagePermissions")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageVacancies")
                        .HasColumnType("boolean");

                    b.HasKey("Secret");

                    b.ToTable("AuthenticationTokens");
                });

            modelBuilder.Entity("Mcc.Bot.Service.Models.Vacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OwnerUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vacancies");
                });
#pragma warning restore 612, 618
        }
    }
}
